#!/bin/bash
# Scaffold a new project for Ralph loop development
# Usage: ./scaffold.sh <target-directory> [project-name]

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
KICKOFF_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
TEMPLATES_DIR="$KICKOFF_DIR/templates"
PROMPTS_DIR="$KICKOFF_DIR/prompts"

# Parse arguments
TARGET_DIR="${1:-}"
PROJECT_NAME="${2:-}"

if [ -z "$TARGET_DIR" ]; then
  echo "Usage: ./scaffold.sh <target-directory> [project-name]"
  echo ""
  echo "Examples:"
  echo "  ./scaffold.sh ~/Projects/movie-tracker"
  echo "  ./scaffold.sh ~/Projects/movie-tracker \"Movie Tracker\""
  exit 1
fi

# Derive project name from directory if not provided
if [ -z "$PROJECT_NAME" ]; then
  PROJECT_NAME=$(basename "$TARGET_DIR" | sed 's/-/ /g' | sed 's/\b\(.\)/\u\1/g')
fi

DATE=$(date +"%Y-%m-%d")

echo ""
echo "============================================"
echo "  Scaffolding Ralph Project"
echo "============================================"
echo "  Target:  $TARGET_DIR"
echo "  Project: $PROJECT_NAME"
echo "============================================"
echo ""

# Create directory structure
echo "Creating directory structure..."
mkdir -p "$TARGET_DIR"/{specs,ralph,archive,src,designs}

# Copy and customize CLAUDE.md
echo "Creating CLAUDE.md..."
sed "s/{{PROJECT_NAME}}/$PROJECT_NAME/g" "$TEMPLATES_DIR/CLAUDE.md.template" > "$TARGET_DIR/CLAUDE.md"

# Create progress.txt
echo "Creating progress.txt..."
sed "s/{{DATE}}/$DATE/g" "$TEMPLATES_DIR/progress.txt.template" > "$TARGET_DIR/progress.txt"

# Create empty IMPLEMENTATION_PLAN.md
echo "Creating IMPLEMENTATION_PLAN.md..."
cat > "$TARGET_DIR/IMPLEMENTATION_PLAN.md" << 'EOF'
# Implementation Plan

<!-- Generated by Ralph planning mode. This file is updated each iteration. -->
<!-- Run `./ralph/ralph.sh plan` to generate or regenerate this plan. -->

## Tasks

_No tasks yet. Run the planning phase to populate._
EOF

# Copy ralph.sh into the project
echo "Copying ralph.sh..."
cp "$KICKOFF_DIR/scripts/ralph.sh" "$TARGET_DIR/ralph/ralph.sh"
chmod +x "$TARGET_DIR/ralph/ralph.sh"

# Copy prompt templates for build/plan modes (discovery/interview stay in kickoff)
echo "Copying prompt templates..."
cp "$PROMPTS_DIR/PROMPT_plan.md" "$TARGET_DIR/ralph/"
cp "$PROMPTS_DIR/PROMPT_build.md" "$TARGET_DIR/ralph/"
cp "$PROMPTS_DIR/PROMPT_plan_work.md" "$TARGET_DIR/ralph/"
cp "$PROMPTS_DIR/PROMPT_discover.md" "$TARGET_DIR/ralph/"
cp "$PROMPTS_DIR/PROMPT_interview.md" "$TARGET_DIR/ralph/"

# Initialize git if not already a repo
if [ ! -d "$TARGET_DIR/.git" ]; then
  echo "Initializing git repository..."
  cd "$TARGET_DIR"
  git init

  # Create .gitignore
  cat > .gitignore << 'GITIGNORE'
# Dependencies
node_modules/
.venv/
__pycache__/

# Environment
.env
.env.local

# Build
dist/
build/
.next/

# OS
.DS_Store
Thumbs.db

# Ralph internal
.last-branch
GITIGNORE

  git add -A
  git commit -m "Initial scaffold: Ralph loop project structure" 2>/dev/null || {
    echo "  Note: Could not create initial commit (git user not configured)."
    echo "  Run: git config user.email 'you@example.com' && git config user.name 'Your Name'"
    echo "  Then: git add -A && git commit -m 'Initial scaffold'"
  }
fi

echo ""
echo "============================================"
echo "  Project scaffolded successfully!"
echo "============================================"
echo ""
echo "Next steps:"
echo ""
echo "  1. cd $TARGET_DIR"
echo "  2. Run the interview to define your project:"
echo "     ./ralph/ralph.sh interview"
echo ""
echo "  3. Generate feature specs from the interview:"
echo "     ./ralph/ralph.sh discover"
echo ""
echo "  4. Create an implementation plan:"
echo "     ./ralph/ralph.sh plan"
echo ""
echo "  5. Start building:"
echo "     ./ralph/ralph.sh build"
echo ""
echo "  Tip: Edit CLAUDE.md to add your project's"
echo "  build/test/lint commands for backpressure."
echo ""
